### ISSUE TITLE
echo messages in gobject's toggleNotify proc

### ISSUE THREAD

**Issue by pekim** [StefanSalewski/nim-gi#1]
I appreciate that the messages can be useful to see the gc reference behaviour. And I guess that they're not intended to stick around forever?

They quickly clutter stdout, and make it a little less easy to see my own temporary messages. So I wonder if while they're still needed they might be put behind a flag of some sort, with a default of not echoing?

If not, it's fine. I can simply continue to comment them out locally.

**Comment by StefanSalewski** [comment]
Thanks for testing. Indeed I think you are the first one who tries it.

As you saw the messages, I assume that you were able to install it successfully?

Please note, the nim-gi package is already replaced by gintro. The core devs where not really happy with the name nim-gi. gintro has now some nimble install support, a few less bugs and an extended tutorial.

Would be great if you can test, and if you can report on which platform you were able to use it.

The nim-gi will be deleted soon -- I let it exist for now, because someone advertised it at reddit, without asking me for permission. As I have no reddit account, I can not add a pointer to ginto. But maybe I should add that pointer to nim-gi README.

And for your question -- that messages will be removed soon, sure. They are there to remind me that I have to do GC stress tests still -- not a very interesting tasks, but important.

**Comment by pekim** [comment]
Yes, I was able install successfully. Your instructions in the README were enough.

Thanks for the pointer to gintro. It is even easier, and was trivial to install and run one of the examples.

I'm using Ubuntu 17.04, which has libgtk 3.22.11.

**Comment by StefanSalewski** [comment]
I have commented out the debugging messages in the gintro package.
